### ISSUE TITLE
README - destroy section is not complete

### ISSUE THREAD

**Issue by gdha** [brainupdaters/fosdem17_workshop#1]
Noticed that the vagrant destroy will stop and delete the VMs, but that does not remove the boxes downloaded, and also explain how to revert the networks added for the workshop.

**Comment by didacog** [comment]
Hi @gdha,
True, I will update this section with your suggestions!
Do you think that the instructions can be followed well? 

Thanks!

**Comment by didacog** [comment]
@gdha 

Do you think is ok now?

Regards,

**Comment by gdha** [comment]
Thanks - I will try it out on a 2th laptop - and will give you feedback
when required (hopefully none)

**Comment by didacog** [comment]
Cool! Many thanks! ;)
